# Generated by Django 5.2.8 on 2025-12-26 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paialuno',
            name='pai',
            field=models.ForeignKey(limit_choices_to={'tipo_usuario': 'pai'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='paialuno',
            unique_together={('pai', 'aluno')},
        ),
    ]
