# Generated by Django 5.2.8 on 2025-12-26 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comunicados', '0001_initial'),
        ('escolas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicado',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escolas.escola'),
        ),
    ]
