# Generated by Django 6.0 on 2025-12-26 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicados', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicado',
            name='destinatarios',
            field=models.ManyToManyField(blank=True, related_name='comunicados_recebidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comunicado',
            name='para_todos',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='remetente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicados_enviados', to=settings.AUTH_USER_MODEL),
        ),
    ]
